server:
  port: 8081

spring:
  h2:
    console:
      enabled: true
      path: /h2

adapters:
  r2dbc:
    host: localhost
    port: 3306
    database: crediya_iam
    username: root
    password: rootpassword

cors:
  allowed-origins: "http://localhost:4200,http://localhost:8081"
